apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    name: redis-svc-cip
    app: demo-voting-app
spec:
  ports:
    - port: 6379
      targetPort: 6379
  selector:
    name: result-pod
    app: demo-voting-app